# Generated by Django 4.2.27 on 2026-01-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image_desktop', models.ImageField(upload_to='banners/desktop/')),
                ('image_mobile', models.ImageField(upload_to='banners/mobile/')),
                ('cta_text', models.CharField(blank=True, default='Explorar Coleção', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, help_text='Optional: if set, banner button links to this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.collection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
