# Generated by Django 4.2.27 on 2026-02-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_vipmarketingsection_vipsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('avatar', models.ImageField(blank=True, help_text='Optional author photo', null=True, upload_to='marketing/testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
