# Generated by Django 4.2.27 on 2026-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', help_text='Selecione imagem ou vídeo para este banner.', max_length=10),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_desktop',
            field=models.FileField(blank=True, help_text="Vídeo para desktop (se media_type for 'video').", null=True, upload_to='banners/video/desktop/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_mobile',
            field=models.FileField(blank=True, help_text="Vídeo para mobile (se media_type for 'video').", null=True, upload_to='banners/video/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text="Usado se media_type for 'image' ou como fallback.", null=True, upload_to='banners/desktop/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text="Usado se media_type for 'image' ou como fallback.", null=True, upload_to='banners/mobile/'),
        ),
    ]
