# Generated by Django 4.2.27 on 2026-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_herobanner_media_type_herobanner_video_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='show_text',
            field=models.BooleanField(default=True, help_text='Se ativado, exibe título, subtítulo e CTA sobre o banner.'),
        ),
    ]
