# Generated by Django 4.2.27 on 2026-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_herobanner_object_position_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='object_position_x',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='object_position_y',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='object_position_x_desktop',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Posição horizontal (desktop).', max_length=10),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='object_position_x_mobile',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Posição horizontal (mobile).', max_length=10),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='object_position_y_desktop',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Fundo')], default='center', help_text='Posição vertical (desktop).', max_length=10),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='object_position_y_mobile',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Fundo')], default='center', help_text='Posição vertical (mobile).', max_length=10),
        ),
    ]
