# Generated by Django 4.2.27 on 2026-08-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='O luxo começa muito antes do primeiro passo.', max_length=200)),
                ('description', models.TextField(default='Cada par Glow Seven nasce de um processo artesanal, onde a experiência, a precisão e a atenção aos detalhes se unem para criar sapatos elegantes, confortáveis e feitos para durar.')),
                ('video_desktop', models.FileField(blank=True, help_text='Vídeo para desktop (MP4, WebM).', null=True, upload_to='marketing/artisan/videos/desktop/')),
                ('video_mobile', models.FileField(blank=True, help_text='Vídeo para mobile (MP4, WebM).', null=True, upload_to='marketing/artisan/videos/mobile/')),
                ('poster', models.ImageField(blank=True, help_text='Imagem de pré-visualização (exibida antes do vídeo carregar).', null=True, upload_to='marketing/artisan/posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
