# Generated by Django 4.2.27 on 2026-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
