# Generated by Django 4.2.27 on 2026-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner large image for category page', null=True, upload_to='categories/banners/'),
        ),
    ]
