# Generated by Django 4.2.25 on 2026-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
