# Generated by Django 4.2.27 on 2026-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='label',
            field=models.CharField(default='COLEÇÃO', help_text='Ex: COLEÇÃO OUTONO', max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='tagline',
            field=models.CharField(blank=True, help_text='Ex: Elegância intemporal', max_length=120),
        ),
    ]
