# Generated by Django 4.2.27 on 2026-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collection_label_collection_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro)'),
        ),
    ]
