# Generated by Django 4.2.27 on 2026-08-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_collection_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagem de capa para a página da coleção', null=True, upload_to='collections/covers/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(help_text='Imagem para a homepage', upload_to='collections/'),
        ),
    ]
