# Generated by Django 4.2.27 on 2026-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_mbwaypayment_multibancopayment_order_mbway_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbwaypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mbwaypayment',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mbwaypayment',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mbwaypayment',
            name='request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mbwaypayment',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='multibancopayment',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='multibancopayment',
            name='entity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='multibancopayment',
            name='reference',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
