# Generated by Django 4.2.27 on 2026-08-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_mbwaypayment_amount_mbwaypayment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multibancopayment',
            name='entity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='multibancopayment',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
