# Generated by Django 4.2.27 on 2026-08-16 18:43

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_multibancopayment_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(db_index=True, default=orders.models.generate_order_ref, editable=False, help_text='Identificador único alfanumérico (8 caracteres).', max_length=8, unique=True),
        ),
    ]
