# Generated by Django 4.2.27 on 2026-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fragrance',
            field=models.CharField(choices=[('sweet', 'Fragrância doce'), ('woody', 'Fragrância amadeirada'), ('none', 'Não quero fragrância')], default='none', help_text='Preferência de fragrância para a encomenda.', max_length=10),
        ),
    ]
