# Generated by Django 4.2.27 on 2026-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller_position',
            field=models.PositiveIntegerField(default=0, help_text='Posição no ranking de Best Sellers (1 = primeiro lugar)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Marcar como Best Seller para aparecer na seção de destaque'),
        ),
    ]
