# Generated by Django 4.2.27 on 2026-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_best_seller_position_product_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, default='Limpar com pano macio e seco. Guardar em local seco e arejado.', help_text='Instruções de cuidados.'),
        ),
        migrations.AddField(
            model_name='product',
            name='heel_height',
            field=models.CharField(blank=True, default='6,5 cm', help_text='Altura do salto (ex: 6,5 cm, 10 cm)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='insole',
            field=models.CharField(blank=True, default='Espuma de alta densidade para máximo conforto', help_text='Descrição da palmilha.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='lining',
            field=models.CharField(blank=True, default='Couro macio respirável', help_text='Descrição do forro.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, default='Couro de alta qualidade com aplicações de cristais.', help_text='Descrição dos materiais utilizados.'),
        ),
    ]
