# Generated by Django 4.2.27 on 2026-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_care_instructions_product_heel_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='object_position_x',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Posição horizontal do foco da imagem/vídeo.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='object_position_y',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Fundo')], default='center', help_text='Posição vertical do foco da imagem/vídeo.', max_length=10),
        ),
    ]
