# Generated by Django 4.2.27 on 2026-08-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_object_position_x_product_object_position_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='object_position_x',
        ),
        migrations.RemoveField(
            model_name='product',
            name='object_position_y',
        ),
    ]
