# Generated by Django 4.2.27 on 2026-09-10 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_object_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo do produto (MP4, WebM ou MOV). Máx. recomendado: 20 MB.', null=True, upload_to='products/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
