# Generated by Django 4.2.27 on 2026-10-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_recommendation',
            field=models.CharField(blank=True, help_text='Recomendação de tamanho exibida abaixo do resumo do produto', max_length=255),
        ),
    ]
