# Generated by Django 4.2.27 on 2026-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stocknotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknotification',
            name='intent',
            field=models.CharField(choices=[('ORDER', 'Quero encomendar'), ('NOTIFY', 'Quero apenas ser notificado')], default='NOTIFY', max_length=10),
        ),
    ]
